name: remote_ssh_command

on: 
  workflow_dispatch
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm git
          sudo rm -rf /opt/nombreDeSuDirectorio
          sudo mkdir -p /opt/nombreDeSuDirectorio
          cd /opt/nombreDeSuDirectorio
          sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/rijmjada/Trello-devSecOps .
          sudo npm install express pm2
          sudo pm2 start index.js
          sudo pm2 status
