name: TruffleHog Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: Scan Results Status
        if: ${{ failure() }}
        run: exit 1
